# 负责检查pull reqests里html文件的Link是否都有效
name: Drop chess pieces
# 触发 workflow 的事件
on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  check-HTML-Links:
    runs-on: windows-2019
    if: startsWith(github.event.issue.title, 'drop,')
    steps:
      - if: startsWith(github.event.issue.title, 'drop,') && contains(github.event.issue.labels.*.name, 'test')
        run: |
          # the triggering issue contains test
          echo "${{ github.event_name }}"
          exit 1

      # 检出代码
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Drop chess pieces...
        run: |
          python gobangProcess.py ${{ github.event.issue.title }} "${{ github.event.issue.user.login }}"


      # Create new commit with the changed files and push it to GitHub
      - name: Commit and push changes
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated game"
          git push
